linters:
  enable:
    - gci

linters-settings:
  gci:
    custom-order: true
    no-inline-comments: false
    no-prefix-comments: false
    sections:
      - prefix(github.com/synesissoftware/CLASP.Go)
      - default
      - standard

run:
  timeout: 5m
